import { Listing, CollectionItem } from '@/types';

// Sample listings data
export const sampleListings: Listing[] = [
  {
    id: '1',
    title: '1943 Steel Penny - Rare Wartime Issue',
    description: 'Authentic 1943 steel penny from World War II era. This rare coin was minted during wartime when copper was needed for the war effort. Excellent condition with minimal wear.',
    price: 1250,
    category: 'coin',
    condition: 'excellent',
    year: 1943,
    country: 'United States',
    images: ['/images/coin1.jpg', '/images/coin1-2.jpg'],
    seller: {
      name: 'John Collector',
      email: 'john@example.com',
      phone: '+1-555-0101',
    },
    createdAt: '2024-01-15',
    status: 'available',
    rarity: 'rare',
  },
  {
    id: '2',
    title: '1914 British Sovereign Gold Coin',
    description: 'Beautiful 1914 British Sovereign in very good condition. This historic gold coin features King George V. A must-have for any serious collector.',
    price: 4500,
    category: 'coin',
    condition: 'very-good',
    year: 1914,
    country: 'United Kingdom',
    images: ['/images/coin2.jpg'],
    seller: {
      name: 'Sarah Numismatics',
      email: 'sarah@example.com',
    },
    createdAt: '2024-01-20',
    status: 'available',
    rarity: 'very-rare',
  },
  {
    id: '3',
    title: '1861 Confederate States $100 Note',
    description: 'Extremely rare Confederate States of America $100 banknote from 1861. This is a genuine piece of American history in excellent condition.',
    price: 8500,
    category: 'note',
    condition: 'excellent',
    year: 1861,
    country: 'Confederate States',
    images: ['/images/note1.jpg', '/images/note1-2.jpg'],
    seller: {
      name: 'Historic Currency Co.',
      email: 'info@historiccurrency.com',
      phone: '+1-555-0202',
    },
    createdAt: '2024-02-01',
    status: 'available',
    rarity: 'extremely-rare',
  },
  {
    id: '4',
    title: '1921 Morgan Silver Dollar',
    description: 'Classic 1921 Morgan Silver Dollar in mint condition. One of the most sought-after coins by collectors worldwide.',
    price: 850,
    category: 'coin',
    condition: 'mint',
    year: 1921,
    country: 'United States',
    images: ['/images/coin3.jpg'],
    seller: {
      name: 'Mike Silver',
      email: 'mike@example.com',
    },
    createdAt: '2024-02-10',
    status: 'available',
    rarity: 'uncommon',
  },
  {
    id: '5',
    title: '1933 Indian 10 Rupee Note',
    description: 'Rare 1933 Indian 10 Rupee banknote featuring King George V. Excellent condition with vibrant colors.',
    price: 3200,
    category: 'note',
    condition: 'excellent',
    year: 1933,
    country: 'India',
    images: ['/images/note2.jpg'],
    seller: {
      name: 'Asian Currency Specialists',
      email: 'contact@asiancurrency.com',
    },
    createdAt: '2024-02-15',
    status: 'available',
    rarity: 'rare',
  },
  {
    id: '6',
    title: '1794 Flowing Hair Silver Dollar',
    description: 'Extremely rare 1794 Flowing Hair Silver Dollar - one of the first silver dollars minted by the United States. This is a museum-quality piece.',
    price: 15000,
    category: 'coin',
    condition: 'very-good',
    year: 1794,
    country: 'United States',
    images: ['/images/coin4.jpg'],
    seller: {
      name: 'Rare Coins Gallery',
      email: 'info@rarecoins.com',
      phone: '+1-555-0303',
    },
    createdAt: '2024-02-20',
    status: 'available',
    rarity: 'extremely-rare',
  },
  {
    id: '7',
    title: '1886 Morgan Silver Dollar - CC Mint',
    description: 'Rare 1886 Carson City Morgan Silver Dollar. The CC mint mark makes this coin highly sought after by collectors.',
    price: 2200,
    category: 'coin',
    condition: 'excellent',
    year: 1886,
    country: 'United States',
    images: ['/images/coin5.jpg'],
    seller: {
      name: 'Western Numismatics',
      email: 'contact@westernnumismatics.com',
    },
    createdAt: '2024-03-01',
    status: 'available',
    rarity: 'very-rare',
  },
  {
    id: '8',
    title: '1909-S VDB Lincoln Cent',
    description: 'Famous 1909-S VDB Lincoln Cent in excellent condition. One of the most iconic American coins.',
    price: 1800,
    category: 'coin',
    condition: 'excellent',
    year: 1909,
    country: 'United States',
    images: ['/images/coin6.jpg'],
    seller: {
      name: 'Historic Coins',
      email: 'info@historiccoins.com',
      phone: '+1-555-0404',
    },
    createdAt: '2024-03-05',
    status: 'available',
    rarity: 'rare',
  },
  {
    id: '9',
    title: '1933 Reichsbanknote 1000 Mark',
    description: 'Historic German Reichsbanknote from the Weimar Republic era. Excellent condition with vibrant colors.',
    price: 2800,
    category: 'note',
    condition: 'excellent',
    year: 1923,
    country: 'Germany',
    images: ['/images/note3.jpg'],
    seller: {
      name: 'European Currency',
      email: 'sales@europeancurrency.com',
    },
    createdAt: '2024-03-10',
    status: 'available',
    rarity: 'rare',
  },
  {
    id: '10',
    title: 'Ancient Roman Denarius - Emperor Trajan',
    description: 'Authentic Roman silver denarius from the reign of Emperor Trajan (98-117 AD). Excellent detail and patina.',
    price: 3200,
    category: 'coin',
    condition: 'very-good',
    year: 110,
    country: 'Roman Empire',
    images: ['/images/coin7.jpg'],
    seller: {
      name: 'Ancient Coins Ltd',
      email: 'info@ancientcoins.com',
      phone: '+1-555-0505',
    },
    createdAt: '2024-03-15',
    status: 'available',
    rarity: 'very-rare',
  },
  {
    id: '11',
    title: '1918 Canadian Large Cent',
    description: 'Beautiful 1918 Canadian Large Cent in mint condition. Rare find with exceptional detail.',
    price: 950,
    category: 'coin',
    condition: 'mint',
    year: 1918,
    country: 'Canada',
    images: ['/images/coin8.jpg'],
    seller: {
      name: 'Canadian Collectibles',
      email: 'info@canadiancollectibles.com',
    },
    createdAt: '2024-03-20',
    status: 'available',
    rarity: 'uncommon',
  },
  {
    id: '12',
    title: '1896 Educational Series $1 Silver Certificate',
    description: 'Rare 1896 Educational Series $1 Silver Certificate. One of the most beautiful banknotes ever issued by the US.',
    price: 12000,
    category: 'note',
    condition: 'excellent',
    year: 1896,
    country: 'United States',
    images: ['/images/note4.jpg'],
    seller: {
      name: 'Paper Money Specialists',
      email: 'info@papermoney.com',
      phone: '+1-555-0606',
    },
    createdAt: '2024-03-25',
    status: 'available',
    rarity: 'extremely-rare',
  },
];

// Sample collection items
export const collectionItems: CollectionItem[] = [
  {
    id: 'c1',
    title: 'Roman Denarius - Emperor Augustus',
    description: 'Ancient Roman silver denarius from the reign of Emperor Augustus (27 BC - 14 AD). A remarkable piece of ancient history.',
    year: 10,
    country: 'Roman Empire',
    images: ['/images/collection1.jpg'],
    category: 'coin',
    rarity: 'extremely-rare',
  },
  {
    id: 'c2',
    title: 'Ming Dynasty Cash Coin',
    description: 'Authentic Chinese cash coin from the Ming Dynasty. This bronze coin features traditional Chinese characters.',
    year: 1400,
    country: 'China',
    images: ['/images/collection2.jpg'],
    category: 'coin',
    rarity: 'very-rare',
  },
  {
    id: 'c3',
    title: '1918 German 1000 Mark Note',
    description: 'Historic German banknote from the Weimar Republic era. This note represents a fascinating period in German economic history.',
    year: 1918,
    country: 'Germany',
    images: ['/images/collection3.jpg'],
    category: 'note',
    rarity: 'rare',
  },
  {
    id: 'c4',
    title: 'Byzantine Gold Solidus',
    description: 'Byzantine gold solidus coin from the 6th century. This coin was used throughout the Byzantine Empire and Mediterranean.',
    year: 550,
    country: 'Byzantine Empire',
    images: ['/images/collection4.jpg'],
    category: 'coin',
    rarity: 'extremely-rare',
  },
];

