import { Listing, CollectionItem } from '@/types';

// Sample listings data
export const sampleListings: Listing[] = [
  {
    id: '1',
    title: '1918 George V One Rupee Silver Coin',
    description: 'A pristine example of the 1918 George V One Rupee. This coin was minted at the Bombay Mint (identified by the dot mint mark). Composed of 91.7% silver, it represents the peak of British Indian coinage. The obverse features the crowned bust of King George V, while the reverse showcases the floral wreath design. A vital piece for any British India collection.',
    price: 3500,
    category: 'coin',
    condition: 'excellent',
    year: 1918,
    country: 'British India',
    images: ['george-v-coin.jpg'],
    seller: {
      name: 'Rajesh Numismatics',
      email: 'rajesh@example.com',
      phone: '+91-98765-43210',
    },
    createdAt: '2024-01-15',
    status: 'available',
    rarity: 'rare',
  },
  {
    id: '2',
    title: '1917 King George V 1 Rupee Note',
    description: 'The legendary 1917 One Rupee banknote, the very first 1 Rupee note issued in India. This specific note bears the signature of M.M.S. Gubbay. It was introduced as a wartime measure due to silver shortages. Includes the original booklet perforation on the left. An extremely rare survivor in this condition.',
    price: 25000,
    category: 'note',
    condition: 'very-good',
    year: 1917,
    country: 'British India',
    images: ['/images/note_1917_1rupee.jpg'],
    seller: {
      name: 'Heritage Notes India',
      email: 'info@heritagenotes.in',
    },
    createdAt: '2024-01-20',
    status: 'available',
    rarity: 'extremely-rare',
  },
  {
    id: '3',
    title: '1862 Victoria Queen One Rupee',
    description: 'A historic 1862 Victoria Queen One Rupee, the first coin series issued directly under the British Crown after the East India Company rule ended. This is the "5 dots" variety, indicating the specific die used. The coin features the "Victoria Queen" legend, which was later changed to "Victoria Empress" in 1877.',
    price: 4500,
    category: 'coin',
    condition: 'excellent',
    year: 1862,
    country: 'British India',
    images: ['victoris-queen-1rs-coin.jpg'],
    seller: {
      name: 'Royal Coins',
      email: 'sales@royalcoins.in',
      phone: '+91-99887-76655',
    },
    createdAt: '2024-02-01',
    status: 'available',
    rarity: 'rare',
  },
  {
    id: '4',
    title: '1970 Food For All 10 Rupees Coin',
    description: 'The 1970 "Food For All" (FAO) 10 Rupees coin is a large silver commemorative issue. It features a lotus and sun design with wheat ears, symbolizing agricultural prosperity. Minted in 80% silver, this was one of the first high-denomination commemorative coins of the Republic of India.',
    price: 2800,
    category: 'coin',
    condition: 'mint',
    year: 1970,
    country: 'Republic India',
    images: ['food-for-all.jpg'],
    seller: {
      name: 'India Mint Collections',
      email: 'mint@example.com',
    },
    createdAt: '2024-02-10',
    status: 'available',
    rarity: 'uncommon',
  },
  {
    id: '5',
    title: 'Mughal Silver Rupee - Akbar',
    description: 'An authentic silver rupee from the golden age of the Mughal Empire, reign of Jalal-ud-din Muhammad Akbar (1556-1605). This coin is from the Ahmedabad mint and features the Ilahi era date. The square area design is characteristic of Akbar\'s later coinage. A tangible piece of 16th-century Indian history.',
    price: 6500,
    category: 'coin',
    condition: 'very-good',
    year: 1580,
    country: 'Mughal Empire',
    images: ['akbar-silver-coin.jpg'],
    seller: {
      name: 'Ancient Treasures',
      email: 'contact@ancienttreasures.in',
    },
    createdAt: '2024-02-15',
    status: 'available',
    rarity: 'very-rare',
  },
  {
    id: '6',
    title: '1939 George VI One Rupee - Silver',
    description: 'The 1939 George VI One Rupee is one of the key dates in the British India series. With the outbreak of WWII, silver content was reduced in later years, making this the last pure silver issue of its type. Highly sought after by investors and collectors alike for its scarcity and historical significance.',
    price: 450000,
    category: 'coin',
    condition: 'excellent',
    year: 1939,
    country: 'British India',
    images: ['/images/coin_1939_rupee.jpg'],
    seller: {
      name: 'Elite Numismatics',
      email: 'elite@rarecoins.in',
      phone: '+91-91234-56789',
    },
    createdAt: '2024-02-20',
    status: 'available',
    rarity: 'extremely-rare',
  },
  {
    id: '7',
    title: 'Fancy Number 100 Rupees Note (786786)',
    description: 'A modern gem for currency collectors: a fresh 100 Rupees note featuring the holy "786" prefix repeated twice (786786). Such fancy serial numbers are highly prized in the Indian market for their numerological significance and rarity. Condition is uncirculated (UNC).',
    price: 5000,
    category: 'note',
    condition: 'mint',
    year: 2023,
    country: 'Republic India',
    images: ['fancy-786-100rs-note.jpg'],
    seller: {
      name: 'Lucky Notes',
      email: 'lucky@notes.in',
    },
    createdAt: '2024-03-01',
    status: 'available',
    rarity: 'rare',
  },
  {
    id: '8',
    title: '1954 1 Pice - Horse Coin',
    description: 'The 1954 Bronze 1 Pice is a beloved small coin from the early Republic era. It features the iconic "Galloping Horse" design, which was only used for a short period. This coin is in excellent condition, retaining its original copper luster, which is rare for bronze coins of this age.',
    price: 1200,
    category: 'coin',
    condition: 'excellent',
    year: 1954,
    country: 'Republic India',
    images: ['horse-coin.jpg'],
    seller: {
      name: 'Desi Coins',
      email: 'info@desicoins.com',
      phone: '+91-88888-99999',
    },
    createdAt: '2024-03-05',
    status: 'available',
    rarity: 'uncommon',
  },
  {
    id: '9',
    title: 'British India 10 Rupees Note - George VI',
    description: 'A rare 10 Rupees banknote from the British India era, featuring the front-facing portrait of King George VI. This note bears the signature of C.D. Deshmukh, the first Indian Governor of the RBI. It represents the transition period towards Indian independence.',
    price: 12000,
    category: 'note',
    condition: 'very-good',
    year: 1944,
    country: 'British India',
    images: ['british-10rs-note.jpg'],
    seller: {
      name: 'Vintage Paper',
      email: 'sales@vintagepaper.in',
    },
    createdAt: '2024-03-10',
    status: 'available',
    rarity: 'rare',
  },
  {
    id: '10',
    title: 'Mauryan Punch Marked Coin',
    description: 'A fascinating silver Karshapana from the Mauryan Empire (approx. 321-185 BC). These are among the earliest coins of India. This specimen features five distinct punch marks including the sun, a six-armed symbol, and a hill symbol. A true piece of ancient history.',
    price: 3500,
    category: 'coin',
    condition: 'very-good',
    year: -300,
    country: 'Ancient India',
    images: ['maurya-punch-coin.jpg'],
    seller: {
      name: 'History Circle',
      email: 'info@historycircle.in',
      phone: '+91-77777-66666',
    },
    createdAt: '2024-03-15',
    status: 'available',
    rarity: 'very-rare',
  },
  {
    id: '11',
    title: '1985 Indira Gandhi 50 Paise',
    description: 'A commemorative 50 Paise coin issued in 1985 to honor the late Prime Minister Indira Gandhi. Minted in ferritic stainless steel. While common in circulation, high-grade specimens like this are becoming harder to find.',
    price: 500,
    category: 'coin',
    condition: 'mint',
    year: 1985,
    country: 'Republic India',
    images: ['indira-gandhi-50-paise1.jpg'],
    seller: {
      name: 'Coin Bazaar',
      email: 'info@coinbazaar.in',
    },
    createdAt: '2024-03-20',
    status: 'available',
    rarity: 'common',
  },
  {
    id: '12',
    title: '1000 Rupees Note - Demonetized',
    description: 'An original 1000 Rupees banknote from the Mahatma Gandhi Series, which was demonetized in November 2016. Sold strictly as a collectible item for numismatic purposes. A significant artifact of India\'s modern economic history.',
    price: 2000,
    category: 'note',
    condition: 'excellent',
    year: 2015,
    country: 'Republic India',
    images: ['1000-rs-note.jpg'],
    seller: {
      name: 'Modern Collections',
      email: 'info@moderncollections.in',
      phone: '+91-66666-55555',
    },
    createdAt: '2024-03-25',
    status: 'available',
    rarity: 'uncommon',
  },
];

// Sample collection items
export const collectionItems: CollectionItem[] = [
  {
    id: 'c1',
    title: 'British India Silver',
    description: 'Victoria, Edward VII, George V & VI Silver Coins',
    year: 1900,
    country: 'British India',
    images: ['/images/collection_british_india.jpg'],
    category: 'coin',
    rarity: 'rare',
  },
  {
    id: 'c2',
    title: 'Republic India Rare',
    description: 'First issues, Commemoratives & Proof Sets',
    year: 1950,
    country: 'Republic India',
    images: ['/images/collection_republic.jpg'],
    category: 'coin',
    rarity: 'very-rare',
  },
  {
    id: 'c3',
    title: 'Ancient & Mughal',
    description: 'Punch-marked, Gupta, Sultanate & Mughal Era',
    year: 1500,
    country: 'Ancient India',
    images: ['/images/collection_ancient.jpg'],
    category: 'coin',
    rarity: 'extremely-rare',
  },
  {
    id: 'c4',
    title: 'Rare Banknotes',
    description: 'British India, Princely States & Early Republic',
    year: 1920,
    country: 'India',
    images: ['/images/collection_notes.jpg'],
    category: 'note',
    rarity: 'rare',
  },
];

